name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed
  $CHANGES

categories:
  - title: "⚡ Breaking"
    label: "major"
  - title: "🚀 New Features"
    label: "feature"
  - title: "✨ Workflow Updates"
    label: "workflow"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"

exclude-labels:
  - "skip-changelog"
