name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed
  $CHANGES

categories:
  - title: "⚡ Breaking"
    labels: "major"
  - title: "🚀 New Features"
    labels: "feature"
  - title: "✨ Workflow Updates"
    labels: "workflow"
version-template: "$MAJOR.$MINOR"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"

exclude-labels:
  - "skip-changelog"
