version-template: "$MAJOR.$MINOR"
name-template: "v$NEXT_MINOR_VERSION"
tag-template: "v$NEXT_MINOR_VERSION"
template: |
  # What's Changed
  $CHANGES

categories:
  - title: "⚡ Breaking"
    label: "major"
  - title: "🚀 New Features"
    label: "feature"
  - title: "🐞 Bug Fixes"
    label: "patch"
  - title: "✨ Workflow Updates"
    label: "workflow"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "patch"

exclude-labels:
  - "skip-changelog"
